### ISSUE TITLE
Adding Insurance to an order

### ISSUE THREAD

**Issue by AylaNicole87** [pemoulton/ShippingHub#64]
Currently we need to add insurance to some Purchasing Power orders. At this time we are doing it manually on the UPS shipping service. Can this be added to the hub?

**Comment by pemoulton** [comment]
OI table is in place and the value of the items is used to populate the DApackageValue

**Comment by pemoulton** [comment]
if DAinsurance='Y' then DApackageValue (based on the Order_items table) is populated into the Insured value.

Although the label does not say it the value was confirmed being passed to the UPS server.
<PackageServiceOptions>
         <DeliveryConfirmation>
           <DCISType>2</DCISType>
         </DeliveryConfirmation>
         <InsuredValue>
           <CurrencyCode>USD</CurrencyCode>
           <MonetaryValue>1093</MonetaryValue>
         </InsuredValue>
       </PackageServiceOptions>
